name: Terraform AWS Organisation

on:
  push:
    branches:
      - main  # Trigger only when there is a push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.6.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform format
      run: terraform fmt

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply --auto-approve
